// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAN6n_2JbWsQ-WJ514hx7XWGydxmwxkfg',
    appId: '1:430246453288:web:de29564cde2cbfbe4a151d',
    messagingSenderId: '430246453288',
    projectId: 'fir-7afc2',
    authDomain: 'fir-7afc2.firebaseapp.com',
    storageBucket: 'fir-7afc2.appspot.com',
    measurementId: 'G-JNJFE545Z5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbufc1o3TOV9s-MOKcn6JjTS6lo-PhXfo',
    appId: '1:430246453288:android:36f94a4357c234894a151d',
    messagingSenderId: '430246453288',
    projectId: 'fir-7afc2',
    storageBucket: 'fir-7afc2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClIWQCtzydADmh60VBJohSe8AJAnCHA5A',
    appId: '1:430246453288:ios:950dd882134439044a151d',
    messagingSenderId: '430246453288',
    projectId: 'fir-7afc2',
    storageBucket: 'fir-7afc2.appspot.com',
    iosClientId: '430246453288-ve6snmo17hvki45l1c17j5mphe3niqe2.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseAuthMy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClIWQCtzydADmh60VBJohSe8AJAnCHA5A',
    appId: '1:430246453288:ios:950dd882134439044a151d',
    messagingSenderId: '430246453288',
    projectId: 'fir-7afc2',
    storageBucket: 'fir-7afc2.appspot.com',
    iosClientId: '430246453288-ve6snmo17hvki45l1c17j5mphe3niqe2.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseAuthMy',
  );
}
